version: '2.1'
services:
  kong:
    build:
      context: ./kong/
    depends_on:
      kong-database:
        condition: service_healthy
    links:
      - kong-database:kong-database
      - wahhoi-api:wahhoi-api
    ports:
      - "8000:50080"
      - "8001:50081"
      - "8443:50443"
      - "8444:50444"
  kong-database:
    image: postgres:9.6
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
  wahhoi-api:
    build:
      context: ./wahhoi-api/wahhoi-api/
    environment: 
      - "spring.datasource.url=jdbc:mysql://wahhoi-api-database:3306/wahhoi"
      - "spring.datasource.username=root"
      - "spring.datasource.password=${MYSQL_ROOT_PASSWORD}"
      - "spring.datasource.driverClassName=com.mysql.jdbc.Driver"
    ports:
      - 8080:8080
    links:
      - wahhoi-api-database:wahhoi-api-database
  wahhoi-api-database:
    build:
      context: ./wahhoi-api/wahhoi-store/
    volumes:
      - ./wahhoi-api/wahhoi-store/sqls:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}