apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: kong
spec:
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 1337
        env:
        - name: DB_ADAPTER
          value: postgres
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: kong
        - name: DB_PASSWORD
          value: kong
        - name: NODE_ENV
          value: development
---
apiVersion: v1
kind: Service
metadata:
  name: konga
  namespace: kong
spec:
  type: LoadBalancer
  selector:
    app: konga
  ports:
  - name: konga
    port: 80
    targetPort: 1337
    protocol: TCP
  - name: konga-secure
    port: 443
    targetPort: 1337
    protocol: TCP
