version: '2.1'
services:
  kong:
    build:
      context: .
    depends_on:
      kong-database:
        condition: service_healthy
    links:
      - kong-database:kong-database
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
  kong-database:
    image: postgres:9.6
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3